---
title: Assessment
type: "generic_page"
---

# Course assessment

Students will be assessed on the basis of the following components:

- One-page summaries of three sessions from the first part of the course. Summaries are to be handed in electronically by the day before the following session at the latest. Summaries will not be graded, however, students must hand them in in order to qualify for the other assignments;

- [**40%**] The presentation of a research paper from the second part of the course. Papers will be presented in small groups (2-4 people, depending on the number of attendants). The presentation will be assessed by the course instructor as well as by the students themselves;

- [**60%**] A short research report-like assignment focusing on one of the studies presented in class in the second part of the course. Students must report on a paper they have not presented themselves. Assignments will be assessed by the course instructor.


# Assessment material

- Template for the session summaries ([here](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S01/Summary-S01.Rmd));

- Assessment rubric for the written assignments ([here](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/Ass-rubric-summary.pdf));

- Assessment rubric for the paper presentations ([here](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/Ass-rubric-presentation.pdf));

- Questions for the report assignment ([here](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/Reference-final-assignment.pdf)).

- Sample report assignment ([here](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/Sample-final-assignment.pdf)).


<div class="alert">
The course instructor will upload a summary of each session by the beginning of the following session.
</div>
