---
title: Syllabus
type: "generic_page"
---

# Course syllabus

Part I --- Foundations of psycholinguistics

- Session 1: What is psycholinguistics? What do psycholinguists investigate? ([Cutler, Klein & Levinson, 2005](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S01-Cutler,Klein&Levinson(2005).pdf))

- Session 2: Why and how to investigate linguistic meaning using psycholinguistic tools? ([Noveck & Reboul, 2008](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S02-Noveck&Reboul(2008).pdf))

- Session 3: Investigating language production ([Gibbs & Van Orden, 2012](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S03-Gibbs&VanOrden(2012).pdf))

- Session 4: Investigating language comprehension ([Schumacher, 2018](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S04-Schumacher(2018).pdf))

- Session 5: Investigating the relation between production and comprehension ([Gambi & Pickering, 2018](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S05-Gambi&Pickering(2018).pdf))

- Session 6: Modeling psycholinguistic data ([Crocker, 2005](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S06-Crocker(2005).pdf))

Part II --- Selected readings

- Session 7: Production studies ([Clarke, Elsner & Rohde, 2013](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S07-Clarke,Elsner&Rohde(2013).pdf); [Domaneschi, Romero & Braun, 2017](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S07-Domaneschi,Romero&Braun(2017).pdf))

- Session 8: Self-paced reading studies ([Bergen & Grodner, 2012](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S08-Bergen&Grodner(2012).pdf); [Rubio-Fernandez, 2013](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S08-Rubio-Fernandez(2013).pdf))

- Session 9: Visual world eye-tracking studies ([Kurumada, Brown, Bibyk, Pontillo & Tanenhaus, 2014](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S09-Kurumada,Brown,Bibyk,Pontillo&Tanenhaus(2014).pdf); [van Bergen & Bosker, 2018](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S09-vanBergen&Bosker(2018).pdf))

- Session 10: Mouse-tracking studies ([Dale & Duran, 2011](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S10-Dale&Duran(2011).pdf); [Tomlinson, Bailey & Bott, 2013](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S10-Tomlinson,Bailey&Bott(2013).pdf))

- Session 11: Timing in turn-taking as a window into the production-comprehension interface ([Levinson & Torreira, 2015, pp.10-24](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S11-Levinson&Torreira(2015).pdf))

- Session 12: Modeling production data ([Herbstritt & Franke, 2019](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S12-Herbstritt&Franke(2019).pdf))

- Session 13: Discourse, cognition and human interaction ([Levinson, 2006](https://github.com/vini-macuch-silva/intro-to-psycholinguistics/tree/master/materials/S13-Levinson(2006).pdf))


