---
output:
  pdf_document: default
  html_document: default
---

# Session 2 - Investigating linguistic meaning using psycholinguistic tools

***

We began the session by situating pragmatics within the larger scope of the language sciences. As a field of research, pragmatics encompasses many approaches and traditions, the main point of contact between pragmaticians of differet strands being an interest in investigating how language understanding goes beyond the mere understanding of words and grammar. Arguably, understanding the meaning of an utterance -- a unit of linguistic meaning at the level of discourse -- involves inferring conclusions, acceding to indirect requests and referring to entitites and events. One way of more clearly delineating the problem is to think of utterance understanding as a process of generating hypotheses about the communicative intentions of one's interlocutor. As Noveck & Reboul (2008) put it, "understanding utterances involves understanding the communicative (i.e. pragmatic) features of language".

## Paul Grice and his two layers of linguistic meaning

***

We mentioned that much work in pragmatics, including work in the recent tradition of experimental pragmatics, can be traced back to the contributions of philosopher Paul Grice. Grice's main insight was to differentiate between **sentence meaning** and **speaker meaning**, the former pertaining to the semantic properties of a sentence according to the language grammar, the latter pertaining to what a speaker might have intended to communicate by uttering a sentence. Under this approach, linguistic communication can be regarded as a process of attributing mental states to interlocutors.

Aside from two levels of meaning, Grice also proposed that communication rests on a **principle of cooperation**, whereby interlocutors "make (their) conversational contribution such as is required, at the stage at which it occurs, by the accepted purpose of direction of the talk exchange in which (they) are engaged". This principle is further explained by his maxims of conversation, such as the Maxims of Quantity -- "Make your contribution as informative as is required and not more informative than is required", or the Maxims of Quality -- "Do not give information that is false or that is not supported by evidence". Thus, according to the Gricean approach, going from sentence meaning to speaker meaning involves making inferences that are guided by expectations that a speaker has attended to heuristics such as the conversational maxims put forward by Grice himself. 

Despite its seminal role in kickstarting pragmatics, Grice's theory of linguistic meaning cannot generate specific experimental predictions. As we discussed, this would be achieved by a subsequent wave of empirical investigation that bridged the world of theoretical pragmatics with the world of cognitive science and experimental psycholinguistics. We looked at two concrete case studies of how pragmatic phenomena can be investigated experimentally, namely the case of scalar implicatures and definite reference.

### Scalar implicatures

***

We started our discussion about inferences with scalars with the following example: if someone utters a sentence of the sort "I saw some of your children today", what is generally thought to be meant is "I did not see all of your children today", since if the speaker had meant "all of the children" she would have used the more informative term 'all' instead. This sort of common inference, a narrowing of semantic meaning, was described by Grice as a **generalized conversational implicature**, that is, as a pragmatic inference that is linked to a common proposition, being pragmatically though not strictly logically valid.

Grice's ideas about generalized conversational implicatures have been further analyzed and enriched. One influential account that builds on his notions was developed by the linguist Laurence Horn, who argued that generalized implicatures are derived on the basis of linguistic scales composed of sets of expressions ranked by degrees of informativeness, such as the scale \<some, all\>, where 'all' is more informative than 'some', at least when considering the scale alone. In that sense, when a speaker uses a term that is ranked lower in terms of informativity (e.g. 'some'), then she is generally considered to imply that the proposition expressed by a more informative term (e.g. 'all') is false. This can be extended to linguistic scales of all sorts, such as scales comprised of logical operators 
(\<'and', 'or\>) or adjectives (\<good, excellent\>). Precisely because of their scalar nature have these inferences been called "scalar implicatures".

Another influential account that builds on the work of Grice was developed by the anthropologist Stephen Levinson. Levinson proposed that scalar implicatures are generated automatically whenever a weak term is used, and that they may be cancelled when a speaker intends the hearer to access the semantic meaning of a given expression. A similar proposal was put forward by the linguist Gennaro Chierchia and his colleagues, where implicatures, as a feature of grammatical systems, are the inferential default except in specific grammatical configurations, collectively known as downward entailing contexts (e.g. negation, question forms, conditional antecedents). Breaking away with the so-called neo-Gricean tradition started by Horn, Dan Sperber and Deidre Wilson, an anthropologist and a linguist, respectively, proposed a drastically new way of thinking about implicatures, one where semantic narrowing does not rely on a general and automatic mechanism but rather on context and communicative relevance. Importantly, what this means is that narrowing need not happen, which in turn means that the semantic meaning does not require cancellation and that the pragmatically narrowed meaning is in fact more effortful than the non-narrowed meaning. As we discussed, it was within this so-called post-Gricean theoretical environment that most experimental work on scalar implicatures has been carried out.

The primary finding to emerge from the experimental literature on adult processing of scalar implicatures has been that pragmatic enrichment implies processing effort. Indeed, the first experimental pragmatic studies showed, for instance, that people take longer classifing underinformative sentences as false compared to classifying them as true (Bott & Noveck, 2004), or that they take longer reading a phrase when the preceding linguistic context supports a narrowed reading (Breheny et al., 2006), which suggests that narrowed readings are more effortful than semantic ones. All in all, what this illustrates is that experiments allow researchers to determine which Gricean-inspired pragmatic theory best makes sense of empirical behavioral data.

### Definite reference

***

In referential usages of language, such as when people refer to objects, utterance interpretation is usually semantically underdetermined. As such, reference, as a case of utterance interpretation, naturally lends itself to analysis in terms of Gricean inference-making. One key constraint put forward in the study of reference resolution is **common ground**, also known as **mutual knowledge**, which is understood to be knowledge common to all involved conversational parties, and regarded as common by all those parties. But does common ground directly constrain linguistic interpretation or does it come into play only when needed? As we discussed, there are two views on this foundational question.

One view is that common ground is intrinsic to mutual understanding, so much so that it forms the core of all reference resolution. Psycholinguist Herb Clark and his colleagues have developed two of the seminal paradigms associated with this view. The first of the two consists of using repeated reference as a measure of production; more specifically, two interlocutors exchange descriptions and information in a task where they are told to organize sets of pictures into particular orders. This paradigm has yielded the finding that not only can reference be made more or less specific depending on contextual needs, but also that once interlocutors agree on specific referential expressions they continue to use those conventionalized expressions even if they seem overinformative, which is known as **lexical entrainment**. The second paradigm developed by Clark and colleagues consists of measuring comprehension in a task where addressees are asked to pick out a referent based on questions. The main finding yielded by this paradigm is that the form of a question presupposes what is part of common ground, thus enabling an addressee to pick out the salient reference. 

The specific processes behind an addressee's reference resolution have been a topic of much debate, and it has been proposed that listeners do not automatically take into consideration a speaker's point of view. Evidence from eye-tracking studies, for instance, shows that listeners fixate objects which they know are not in common ground with their interlocutors before fixating on an intended referent (Keysar et al., 1998, 2003). Other eye-tracking studies have provided evidence in favor of a strong common ground approach, where, for example, people were shown to exploit linguistic cues early on in processing, using those cues to engage in theory-of-mind reasoning in real time (e.g. Hanna et al., 2003). All in all, what this illustrates is that referential language alone cannot provide listeners with all the necessary clues needed to arrive at pragmatic understanding. Some amount of inference is needed to close the gap between sentence meaning and speaker meaning.

### Investigating pragmatic interpretation experimentally

***

The case studies of scalar implicatures and definite reference illustrate what factors are at play in the analysis of pragmatic language interpretation, namely the communicaive conventions shared by language users, that is, the linguistic expressions they use, the inferences they draw in context, and the intentions they ascribe to one another. In the case of scalars, the focus in the literature has been mostly on the relative importance of conventions and inferences, while in the case of definite reference it has been mostly on the extent to which theory of mind, or perspective-taking, matters in sentence interpretation. Common to both debates is the polarization between those who defend an effortful approach to the derivation of speaker meaning and those who consider that language itself resolves meaning. Within this scenario, the study of experimental pragmatics seems particularly relevant, as it promises to inform the field of linguistic pragmatics, to allow the study of features which are not usually studied under traditional psycholinguistic research, and due to its overarching Gricean framework to extend to a wide variety of topics, including topics usually studied in isolation within individual cognitive scientific disciplines. Ultimately, then, experimental pragmatics holds the promise of a wider integration between different branches of the cognitive sciences.