---
output:
  pdf_document: default
  html_document: default
---

# Session 3 - Psycholinguistic methods: An overview

***

In this session we briefly explored three behavioral methods commonly employed in psycholinguistic research: self-paced reading, visual world eye-tracking and mouse-tracking. As discussed at the onset of the class, psycholinguistics is a primarily experimental and quantitative discipline, which is why we focus on experiments as a means of analyzing linguistic behavior. Other quantitative methods such as neuroimaging and computational modeling are becoming increasingly more common in psycholinguistic research, although these tools are usually used in addition to or in conjunction with behavioral methods such as the ones covered in this course. 

Our main goal in overviewing these different methods is to understand the purpose and usefulness of experimental behavioral methods as tools for psycholinguistic investigation. In other words, our aim is to understand when a method can best be used, for instance, to tackle pragmatic processing in the context of reading or listening. In order to understand the link between a behavioral measure and a theory or model of a particular phenomenon, we reflect on the specific experimental tasks that participants are asked to perform, such as reading a sentence and then answering a comprehension question, or looking at a visual display while listening to a description and then choosing an appropriate object as the target of that same description. 

## Self-paced reading

***

Self-paced reading (SPR) is a computerized method of recording **reading times** for segments of sentences -- either individual words or larger sentence chunks like phrases -- presented as linguistic stimuli in experiments. Reading is said to be self-paced because participants decide the pace at which they read each presented segment, usually pressing a key to move from one sentence segment to the next. Sentence segments are typically represented by dashes or underlines which mask the exact words or phrases contained behind them. Each button press reveals one sentence segment, such that a new reading chunk is unmasked. Despite there being different types of displays, most SPR studies now employ non-cumulative linear displays, also known as the moving window technique, which counteract a parsing strategy where participants simply reveal several segments before reading them as a whole.

In self-paced reading, the eyes are taken as a window onto cognition, resting on the assumption that the time taken to read a word reflects the time needed to process that word. Although this assumption oversimplifies the intricacies of the relation between reading and processing, it allows experimentalists to use reading times, a specific class of reaction time data, as an inferential springboard from which to draw conclusions about the cognitve processing of [written] language. The basic inference is that longer reading times indicate processing difficulty, while faster reading times indicate facilitation. Processing difficulties in SPR paradigms can arise as a result of encountering one of three things: an ambiguous reading segment, an anomalous reading segment, or what is known as a distance dependency. 

**Ambiguities** in reading arise when the grammar of a language allows multiple syntactic interpretations of a single word or phrase in a given sentence environment. In the majority of cases, parsing will be skewed towards one reading and not the other, resulting in an observable processing strategy which can then be linked to the underlying structural representation. **Anomalies** include grammar violations as well as inconsistent or non-canonical permutations of different kinds of linguistic stimuli, from word order and syntactic elements to semantic and discourse elements. **Distance dependencies** stand for the recognition or computation of a syntactic relationship between two linguistic elements that are not adjacent linearly. Taken together, these different paradigms can be employed to study a variety of questions concerned with the processing of language, such as whether parsing operates sequentially or in terms of multiple plausible interpretations, whether all types of linguistic information are integrated at once or whether structure has priority over meaning, whether heuristics can motivate different processing strategies, and to what extent processing mechanisms and strategies might vary cross-linguistically.

## Visual world eye-tracking

***

Eye-tracking is a method widely used in psychological and cognitive scientific research. Its relevance for the study of speech perception and language processing has been noted as early as in the 1970s, though only in the 1990s did it become widespread in the field of psycholinguistics. The visual world paradigm, an eye-tracking paradigm where the relationship between eye movements and language comprehension is explored in relation to a display containing objects or various sorts of visual scenes, is a powerful tool to investigate how linguistic and non-linguistic factors jointly affect the understanding of language.

The setup of a visual world eye-tracking study usually involves participants listening to an utterance on each trial while they look at an experimental display and their eye movements are recorded. The visual displays participants look at can contain semi-naturalistic scenes composed of several objects and agents, sets of individual objects -- which in some cases are presented physically during the experiment instead of being presented on a computer screen, but also written words. In most visual world implementations, the displays contain both targets -- which are objects mentioned explicitly in the linguistic stimulus -- and distractors -- which are objects that may be related to targets either semantically/ conceptually or phonologically/ orthographically. Depending on the specific experimental task at hand, the spoken stimuli are either treated as instructions -- as in the case of "direct action" tasks -- or as comments or descriptions of the displays -- as in "look and listen" tasks. The main advantage of the visual world paradigm compared to other traditional psycholinguistic methods is that it does not involve asking participants for metalinguistic judgments. Instead, it capitalizes on people's tendency to look at specific areas of a visual display as they listen to a linguistic signal unfold in real time -- which in turn reveals their underlying preferences for certain visually present objects and not others.

Participants' visual attention is measured in visual world experiments in terms of the relative likelihood of them looking at certain regions of interest at different times during a trial. Proportions or counts of quick movements of the eyes -- known as saccades -- are then compared across regions of interest for a given time window. Ultimately, this gives researchers an insight into how language users' eye movements are systematically related to their online processing of language.

## Mouse-tracking

***

Eye-tracking, despite being incredibly powerful and flexible as a method of investigating language comprehension, depends primarily on the interpretation of saccades and fixations. Saccadic eye movements are generally ballistic, which is to say that they rapidly shift the focus of visual attention from one point to another. In a visual world paradigm, that translates in the quick re-directing of fixations towards different regions of interest and only rarely in fixations on blank regions in between potential referential targets. Mouse-tracking, the streaming of x, y coordinates of computer mouse movements, offers a continuous view of non-ballistic trajectories. Much like in the case of eye movements, movements of the arm and hand can serve as an indicator of the cognitive processes underlying language processing, however, unlike saccadic eye movements, they have the advantage of showing more pronounced curvatures due to the non-linear nature of the resulting mouse trajectories. More importantly, mouse-tracking affords more data points per second compared to both eye-tracking and self-paced reading, providing, ultimately, a much more continuous view of online processing.
