---
output:
  pdf_document: default
  html_document: default
---

# Session 5 - Investigating language comprehension at the discourse level

***

In this session, we extended our empirical and theoretical coverage of pragmatic phenomena, looking at some new case studies of pragmatic interpretation and attemtping to integrate different phenomena in terms of similar explanatory principles. We focused our attention on pragmatic inferences and referece resolution.

# Reference resolution

***

When discussing reference resolution, we started by highlighting the basics of reference-making in linguistic communication: referents are introduced in discourse and they can be subsequently taken up or referred back to. The **information status** of referents is of central importance to the resolution of reference in language comprehension. Traditionally, referents have been thought of in terms of a new-given dichotomy, where, for example, in languages that have definiteness marking the introduction of new referents would be realized with an indefinite marker (e.g. Here's *a* referent), while reference to a referent already introduced would be realized with a definite marker (e.g. Now referring back to *the* referent from above). Such distinction proved insufficient in capturing empirical patterns such as the usage of a definite marker to introduce a new referente that is semantically related to another referent which is already given in discourse. These patterns suggest a more nuanced understanding of the new-given relation, where partly new vs. partly given information lie on a continuum of givenness. From an experimental perspective, early evidence has indicated that given information is facilitated in online processing compared to given or inferred information.

Givenness is one source of information for the processing system in the weighing of the relative importance of a given referent. Given the processing constraints of language comprehension, referents are assumed to be stored in a given ranked order, which facilitates the access and organization of multiple referents in discourse. The concept of **prominence** can then be invoked to explain the resolution of reference - given a set of referents, the most prominent referent is the one that gets singled out as the most likely referential candidate. Two crucial questions that follow from this notion have to do with the features which contribute to prominence in discourse, and to how speakers refer to refents of different prominence in ongoing discourse. As in the case of production, in comprehension there seems to be an inverse relation between the prominence of a referent and the explicitness of the linguistic forms used by speakers, such that hearers rely on form-specific constraints to track referents in while interpreting language. One specific theory that incorporates these insights is Centering Theory, which postulates that the most prominent referent in prior discourse is the one that is picked up by a pronoun. Evidence for a such a theory comes, for example, from self-paced reading studies showing that a proper name is processed more effortfully than a less explicit pronominal form (Gordon et al., 2003).

The case of pronouns raises interesting questions as for what the role of different factors might be in reference resolution. Indeed, investigating pronouns among other types of referring expressions can be informative with regard to whether a single feature determines referential prominence, or if perhaps multiple weighted features interact in the process of narrowing down referential candidates, but also if mappings may be form-specific in nature. Processing data shows that various features interact in determining the prominence of a given referent. These features stem from various levels of linguistic organization -- such as morphosyntax or semantics -- as well as from other sources of information -- such as information structure or discourse coherence, and as such result in the added complication that many features are intertwined among themselves, such as linear ordering, givenness, and topicality. In psycholinguistic experiments, the solution is to try and isolate a small subset of features in scenarios that are constructed so as to allow only a limited number of potential referential targets -- usually two at most (a target and a competitor). As for the effects of form-specificity on reference resolution, there is evidence that different types of referring expressions lead to asymmetries in interpretation. For example, eye-tracking data shows that comprehenders interpret a personal pronoun (*it*) differenly from a demonstrative (*that*), the pronoun showing a bias for interpretation in terms of a previously introduced referent while the demonstrative being interpreted as referring to a larger semantic unit composed of the given referent plus its location (Brown-Schmidt et al., 2009).

## Pragmatic inferences

***

Inferences are another case in point of how interpretation might be guided by general principles related to brevity, informativity, and relevance. As discussed previously, in the Gricean tradition of pragmatics interpreting a speaker's utterance can be considered a process of reconstructing the speaker's potential intentions behind their utterance. The Gricean principles of communication presuppose a trade-off between saying as much as one can but at the same time no more than is required by the communicative context. For instance, in the setting of a restaurant, a waiter who utters the sentence "The ham sandwich is sitting at Table 20" is taken to assume that their addressee is able to draw the relevant inference from their utterance and thus to arrive at the implied meaning that "The person who ordered the ham sandwich is sitting at Table 20". Such a case of meaning extension, more specifically a meaning transfer or referential transfer, involves a process of reconceptualization from the side of the interpreter, whereby, in this case, the ordered food item is understood as a referential shortcut for the orderer of the food. This notion of reconceptualiztion is supported by a simple coordination test applied to the original utterance which reveals the underlying meaning transfer -- once the order-for-orderer shift has been established the original object-denotation is no longer available, at least not within the same referring expression. Data from neurolinguistic studies shows that while some cases of meaning transfer incur processing costs others don't. The degree of conventionalization of the expressions under analysis seems to modulate the shifts, with frequently used alternations such as content-for-container and producer-for-product not requiring more inferencing, perhaps as a result of integration into lexically coded meaning. Another kind of meaning extension involves a shift from an object-denoting entity to an event, such as in "The girl began the book", usually understood as "The girl began reading the book". A question that begs to be answered is on the basis of what information does such meaning shift occur? Two types of account exist in the literature, those that locate the source of such information in the lexicon itself and those that assume that general inferences and world knowledge come into play. In either case, it seems that one can explain these phenomena of meaning extension in terms of an interplay between the conversational principles of brevity and clarity. Other phenomena might rely on different principles, therefore further research is necessary to understand the explanatory differences and commonalities between different meaning phenomena.

Unlike meaning extensions, implicatures operate at a more global level, arguably depending more strongly on inferreing intended meaning against the background of the conversational setting. As discussed before, scalar implicatures usually evoke processing effort, however, are these implicatures drawn automatically? Different pragmatic theories generate different predictions, and at this point evidence is mixed in that regard. Another type of conversational implicature, particularized implicatures, arise only in certain contexts and rely on common ground between interlocutors. They seem to rely strongly on a principle of relevance, and can also interact with principles of politeness. All in all, both in the case of implicatures and meaning extension as well as in the case reference resolution "reading between the lines" seems to be a necessary capacity for comprehenders, most likely mediated by a variety of conversational principles. The principle of informativeness might capture many of the phenomena discussed so far, relating in part to constraints emerging from efficiency and processing ease as well as to languge users' communicative needs. A general model of meaning that unifies different pragmatic processing phenomena under the same explanatory principles is very much work in progress.
